"""Canonical finite-difference displacement sequence."""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import TYPE_CHECKING

import numpy as np
from ase import Atoms

if TYPE_CHECKING:
    from mlfcs.finite_difference.difference import FiniteDifference


def supercell_atoms(difference: FiniteDifference) -> Atoms:
    supercell = difference.mapping.supercell
    return Atoms(
        numbers=supercell.numbers,
        scaled_positions=supercell.scaled_positions,
        cell=supercell.cell,
        pbc=True,
    )


class Displacements(Sequence[Atoms]):
    """The canonical key-displacement-sign structures generated by one experiment."""

    __slots__ = ("_difference",)

    def __init__(self, difference: FiniteDifference):
        self._difference = difference

    def __len__(self) -> int:
        return self._difference.n_configurations

    def __getitem__(self, index: int | slice) -> Atoms | tuple[Atoms, ...]:
        if isinstance(index, slice):
            return tuple(self[position] for position in range(*index.indices(len(self))))
        position = int(index)
        if position < 0:
            position += len(self)
        if not 0 <= position < len(self):
            raise IndexError("displacement index is outside the finite difference")
        difference = self._difference
        sign_count = len(difference._signs)
        disp_count = len(difference.disps)
        key_index, remainder = divmod(position, disp_count * sign_count)
        disp_index, sign_index = divmod(remainder, sign_count)
        key = difference._keys[key_index]
        disp = difference.disps[disp_index]
        delta = np.zeros((len(difference.mapping.supercell.numbers), 3))
        for sign, (atom, axis) in zip(difference._signs[sign_index], key, strict=True):
            delta[int(atom), int(axis)] += int(sign) * disp
        atoms = supercell_atoms(difference)
        atoms.positions += delta
        atoms.info["mlfcs_id"] = position
        atoms.info["mlfcs_disp"] = disp
        atoms.arrays["mlfcs_displacement"] = delta
        return atoms

    def __iter__(self) -> Iterator[Atoms]:
        for index in range(len(self)):
            yield self[index]


__all__ = ["Displacements", "supercell_atoms"]
