"""Construct symmetry-invariant tensor spaces and physical Cartesian parameterizations.

The module first builds the tensor subspace compatible with repeated-site
index symmetry and the stabilizer of a representative cluster. The resulting
invariant space is represented exactly in lattice coordinates and can then be
converted to Cartesian coordinates and reparameterized by selected physical
tensor components.
"""

from __future__ import annotations

from collections.abc import Sequence

import numpy as np
from numba import njit
from scipy.linalg import qr

from mlfcs.cluster_space.integer_kernel import integer_kernel_basis
from mlfcs.foundation.arrays import as_int64_array, require_allocation
from mlfcs.foundation.tensors import apply_tensor_action, tensor_dimension, validate_tensor_action


def _label_symmetric_basis(labels: Sequence[object]) -> np.ndarray:
    """Build the label-symmetric tensor basis for one representative cluster.

    Tensor slots carrying equal lattice-site labels are interchangeable:
    Cartesian components related only by permutations among equal slots
    share one independent component. The construction is delegated to
    :func:`label_basis`.
    """
    dimension = tensor_dimension(len(labels))
    require_allocation("label basis", (dimension, dimension))
    equal = np.asarray([[a == b for b in labels] for a in labels], dtype=np.uint8).reshape(
        len(labels), len(labels)
    )
    return label_basis(equal)


def compute_invariant_basis(
    labels: Sequence[object],
    stabilizers: Sequence[tuple[np.ndarray, tuple[int, ...]]],
) -> np.ndarray:
    """Construct the exact tensor basis invariant under the cluster stabilizer.

    Let ``p = len(labels)`` and let ``L`` denote the label-symmetric tensor
    basis induced by repeated lattice sites. For every stabilizer operation
    ``g`` with lattice rotation ``R_g`` and tensor-axis permutation ``P_g``,
    the allowed tensors satisfy ``T_g Phi = Phi``, where ``T_g`` is the
    corresponding rank-``p`` tensor action. In the coordinates of ``L``, the
    invariant subspace is therefore the integer kernel of the stacked
    constraints ``(T_g - I) L c = 0`` over all stabilizer operations.

    Parameters
    ----------
    labels
        Lattice-site labels of the representative cluster, one per tensor
        index.
    stabilizers
        Stabilizer operations of the representative cluster. Each entry is
        ``(rotation, permutation)``, where ``rotation`` is a ``(3, 3)``
        integer lattice-coordinate tensor action and ``permutation`` has
        length ``p``.

    Returns
    -------
    ndarray
        Saturated ``int64`` basis of shape ``(3**p, d)``. Its columns span
        exactly the tensor subspace satisfying both repeated-site index
        symmetry and all stabilizer constraints.

    Raises
    ------
    ValueError
        If the stabilizer buffers have inconsistent shapes or an axis action
        is not a permutation.
    OverflowError
        If a rotation's tensor-action bound or the stacked constraint array
        cannot be represented or allocated.
    """
    label_basis = _label_symmetric_basis(labels)
    if stabilizers:
        rotations = as_int64_array([rotation for rotation, _ in stabilizers])
        permutations = as_int64_array([permutation for _, permutation in stabilizers])
        if rotations.shape != (len(stabilizers), 3, 3) or permutations.shape != (
            len(stabilizers),
            len(labels),
        ):
            raise ValueError("stabilizer buffers have inconsistent shapes")
        if not np.all(np.sort(permutations, axis=1) == np.arange(len(labels))):
            raise ValueError("stabilizer axes must be permutations")
        for rotation in rotations:
            validate_tensor_action(rotation, len(labels), subtraction=1)
        require_allocation(
            "invariant constraints", (len(stabilizers) * label_basis.shape[0], label_basis.shape[1])
        )
        constraints = invariant_constraints(label_basis, rotations, permutations)
    else:
        constraints = np.empty((0, label_basis.shape[1]), dtype=np.int64)
    constraints = np.unique(constraints, axis=0)
    kernel = integer_kernel_basis(constraints)
    # Each label-basis row selects exactly one column; this avoids an
    # unnecessary integer dot product and its coefficient-growth bound.
    result = kernel[np.argmax(label_basis, axis=1)]
    return result


__all__: list[str] = []


@njit(cache=True)
def label_basis(equal):
    """Construct the tensor basis generated by repeated-site index symmetry.

    ``equal[i, j]`` indicates whether tensor slots ``i`` and ``j`` refer to
    the same lattice site. Cartesian tensor components that differ only by
    permutations among equal slots are identified as one independent
    component.

    For tensor order ``p``, Cartesian components are flattened in C order,
    giving ``3**p`` rows. The returned matrix has shape ``(3**p, d)``, where
    ``d`` is the number of resulting equivalence classes. Each row contains
    exactly one unit entry, assigning that Cartesian component to its class.
    """
    order = equal.shape[0]
    dimension = 3**order
    classes = np.full(dimension, -1, dtype=np.int64)
    column_of_row = np.empty(dimension, dtype=np.int64)
    count = 0
    for row in range(dimension):
        directions = np.empty(order, dtype=np.int64)
        for i in range(order):
            directions[i] = row // (3 ** (order - 1 - i)) % 3
        for i in range(order):
            for j in range(i + 1, order):
                if equal[i, j] and directions[j] < directions[i]:
                    directions[i], directions[j] = directions[j], directions[i]
        key = 0
        for i in range(order):
            key = 3 * key + directions[i]
        if classes[key] < 0:
            classes[key] = count
            count += 1
        column_of_row[row] = classes[key]
    result = np.zeros((dimension, count), dtype=np.int64)
    for row in range(dimension):
        result[row, column_of_row[row]] = 1
    return result


@njit(cache=True)
def invariant_constraints(seed, rotations, permutations):
    """Assemble linear constraints enforcing stabilizer invariance.

    For each stabilizer operation ``g``, the tensor basis ``seed`` is acted
    on by the corresponding lattice rotation and tensor-axis permutation.
    Invariant coefficients ``c`` satisfy ``(T_g - I) seed @ c = 0``; the
    returned matrix stacks ``(T_g - I) seed`` over all operations. Inputs
    are preserved and not validated: allocation and rotation-bound
    admission belong to the caller, which also removes zero and duplicate
    rows.
    """
    rows, columns = seed.shape
    result = np.empty((len(rotations) * rows, columns), dtype=np.int64)
    for operation in range(len(rotations)):
        transformed = apply_tensor_action(seed, rotations[operation], permutations[operation])
        for i in range(rows):
            for j in range(columns):
                result[operation * rows + i, j] = transformed[i, j] - seed[i, j]
    return result


def component_parameterization(cartesian: object) -> tuple[np.ndarray, np.ndarray, float]:
    """Reparameterize a Cartesian tensor subspace by physical tensor components.

    Let ``cartesian`` span a ``d``-dimensional subspace of the flattened
    Cartesian tensor space. This function selects ``d`` tensor-component rows
    whose restriction is nonsingular and constructs an equivalent basis
    ``B`` satisfying ``B[rows, :] = I``. Consequently, the parameter vector
    in ``Phi_flat = B @ coefficients`` is exactly the set of selected
    Cartesian tensor components ``Phi_flat[rows]``.

    Parameters
    ----------
    cartesian
        Finite two-dimensional array with ``d`` columns whose columns span
        the Cartesian tensor subspace.

    Returns
    -------
    basis
        Equivalent floating-point basis with the same shape as ``cartesian``
        satisfying ``basis[rows] = I`` up to numerical roundoff.
    rows
        Integer array of shape ``(d,)`` containing the selected Cartesian
        component indices, sorted.
    condition
        Spectral condition number of the selected row block before
        reparameterization.

    Raises
    ------
    ValueError
        If the input is not a finite two-dimensional array or the supplied
        subspace loses its expected numerical rank.

    Notes
    -----
    Rows are selected greedily from an orthonormal basis using modified
    Gram-Schmidt residual norms. The condition number is reported as a
    diagnostic and does not change the subspace dimension.
    """
    values = np.asarray(cartesian, dtype=np.float64)
    if values.ndim != 2 or not np.all(np.isfinite(values)):
        raise ValueError("Cartesian basis must be a finite two-dimensional array")
    rows, dimension = values.shape
    if dimension == 0:
        return np.empty((rows, 0)), np.empty(0, dtype=np.int64), 1.0
    orthonormal, _ = qr(values, mode="economic", check_finite=False)
    selected = select_observation_rows(orthonormal)
    observed = orthonormal[selected]
    basis = np.linalg.solve(observed.T, orthonormal.T).T
    condition = float(np.linalg.cond(observed, 2))
    basis.setflags(write=False)
    selected.setflags(write=False)
    return basis, selected, condition


@njit(cache=True)
def select_observation_rows(orthonormal: np.ndarray) -> np.ndarray:
    """Select independent observation rows by greedy Gram-Schmidt residuals.

    At each step, the available row with the largest squared residual norm is
    selected, then its normalized direction is projected from all remaining
    rows. The procedure selects exactly one row per subspace dimension and
    raises ValueError if fewer than that many numerically independent rows
    can be selected. Inputs have orthonormal columns; the returned row
    indices are sorted.
    """
    rows, dimension = orthonormal.shape
    residuals = orthonormal.copy()
    available = np.ones(rows, dtype=np.uint8)
    selected = np.empty(dimension, dtype=np.int64)
    for column in range(dimension):
        best_row = -1
        best_score = -1.0
        for row in range(rows):
            if available[row] == 0:
                continue
            score = 0.0
            for component in range(dimension):
                score += residuals[row, component] * residuals[row, component]
            if score > best_score:
                best_score = score
                best_row = row
        if best_row < 0 or not best_score > 0.0:
            raise ValueError("Cartesian invariant subspace lost its expected dimension")
        selected[column] = best_row
        available[best_row] = 0
        inverse_norm = 1.0 / np.sqrt(best_score)
        direction = np.empty(dimension, dtype=np.float64)
        for component in range(dimension):
            direction[component] = residuals[best_row, component] * inverse_norm
        for row in range(rows):
            overlap = 0.0
            for component in range(dimension):
                overlap += residuals[row, component] * direction[component]
            for component in range(dimension):
                residuals[row, component] -= overlap * direction[component]
    return np.sort(selected)
