"""Construct symmetry orbits and stabilizers of force-constant clusters.

A cluster is acted on by primitive-cell space-group operations together with
allowed tensor-index permutations. Each transformed image is re-anchored to
remove the common lattice translation. Distinct images form the cluster orbit,
while actions that return the representative define its stabilizer.
"""

import numpy as np
from numba import njit

from mlfcs.cluster_space.model import Cluster
from mlfcs.foundation.arrays import as_int64_array, require_allocation
from mlfcs.geometry.symmetry import PrimitiveSymmetry


@njit(cache=True)
def cluster_hash(labels):
    """Return a deterministic hash used only to accelerate exact label lookup."""
    result = 0
    for value in labels.flat:
        result = (result * 65521 + value % 2147483647) % 2147483647
    return result


@njit(cache=True)
def registry_contains(labels, keys, used):
    """Return whether an exact cluster-label array is present in the hash registry.

    The table uses linear probing and must contain at least one unused slot.
    """
    index = cluster_hash(labels) % len(used)
    while used[index]:
        if np.all(keys[index] == labels):
            return True
        index = (index + 1) % len(used)
    return False


@njit(cache=True)
def registry_insert(values, keys, used):
    """Insert cluster-label arrays into the registry and return the number newly added."""
    added = 0
    for labels in values:
        index = cluster_hash(labels) % len(used)
        while used[index] and not np.all(keys[index] == labels):
            index = (index + 1) % len(used)
        if not used[index]:
            keys[index] = labels
            used[index] = 1
            added += 1
    return added


@njit(cache=True)
def distinct_orbit_actions(values, representative):
    """Identify distinct orbit images and stabilizer actions.

    ``values[i]`` is the cluster image generated by action ``i``. The first
    occurrence of each distinct image is retained as its representative action.
    Actions whose image equals ``representative`` are returned separately as
    stabilizer actions.

    Returns
    -------
    distinct
        Indices of the first actions generating each distinct cluster image.
    stabilizers
        Indices of all actions that leave the representative unchanged.
    """
    capacity = max(2, 2 * len(values))
    keys = np.empty((capacity, values.shape[1], 4), dtype=np.int64)
    used = np.zeros(capacity, dtype=np.uint8)
    indices = np.empty(len(values), dtype=np.int64)
    stabilizers = np.empty(len(values), dtype=np.int64)
    count = stable_count = 0
    for i in range(len(values)):
        if np.all(values[i] == representative):
            stabilizers[stable_count] = i
            stable_count += 1
        if not registry_contains(values[i], keys, used):
            registry_insert(values[i : i + 1], keys, used)
            indices[count] = i
            count += 1
    return indices[:count], stabilizers[:stable_count]


@njit(cache=True)
def transform_cluster(
    labels: np.ndarray,
    rotations: np.ndarray,
    site_permutations: np.ndarray,
    site_shifts: np.ndarray,
    axis_permutations: np.ndarray,
) -> np.ndarray:
    """Apply space-group and tensor-index actions to a cluster.

    For a tensor slot with lattice label ``(i, n)``, a primitive symmetry
    operation ``g`` maps

        i -> sigma_g(i)
        n -> n @ R_g.T + s_g(i),

    where ``sigma_g`` is the motif-site permutation, ``R_g`` is the integer
    lattice rotation, and ``s_g(i)`` is the lattice translation required to
    return the transformed motif site to the reference cell.

    Each allowed tensor-axis permutation is composed with every symmetry
    operation. The resulting image is then re-anchored by subtracting the
    translation of its first tensor slot from all slots, so images differing
    only by a common lattice translation share the same representation.

    Parameters
    ----------
    labels
        Cluster labels of shape ``(p, 4)`` as ``(site, tx, ty, tz)``.
    rotations
        Integer lattice rotations of shape ``(s, 3, 3)``.
    site_permutations
        Primitive-site permutations of shape ``(s, N)``.
    site_shifts
        Lattice image shifts of shape ``(s, N, 3)``.
    axis_permutations
        Tensor-axis permutations of shape ``(q, p)``.

    Returns
    -------
    ndarray
        Integer labels of shape ``(s*q, p, 4)`` in operation-major order.
        Affine and re-anchoring bounds are admitted by the caller before
        entry.
    """
    operation_count = rotations.shape[0]
    permutation_count = axis_permutations.shape[0]
    order = labels.shape[0]
    transformed = np.empty((operation_count * permutation_count, order, 4), dtype=np.int64)
    for operation in range(operation_count):
        for permutation_index in range(permutation_count):
            target = operation * permutation_count + permutation_index
            for axis in range(order):
                source_axis = axis_permutations[permutation_index, axis]
                source_site = labels[source_axis, 0]
                transformed[target, axis, 0] = site_permutations[operation, source_site]
                for component in range(3):
                    value = site_shifts[operation, source_site, component]
                    for inner in range(3):
                        value += (
                            labels[source_axis, inner + 1] * rotations[operation, component, inner]
                        )
                    transformed[target, axis, component + 1] = value
            for component in range(3):
                origin = transformed[target, 0, component + 1]
                for axis in range(order):
                    transformed[target, axis, component + 1] -= origin
    return transformed


class ClusterRegistry:
    """Registry of previously encountered cluster labels for one tensor order.

    The registry provides exact membership and insertion while using hashing
    only as an acceleration mechanism.
    """

    def __init__(self, order):
        """Create an empty registry for clusters of the given tensor order."""
        self.order = order
        self.count = 0
        require_allocation("orbit registry", (16, order, 4))
        self.keys = np.empty((16, order, 4), dtype=np.int64)
        self.used = np.zeros(16, dtype=np.uint8)

    def contains(self, labels):
        """Return whether the cluster labels are already registered."""
        return registry_contains(labels, self.keys, self.used)

    def update(self, labels):
        """Insert cluster labels, growing the registry when necessary."""
        capacity = len(self.used)
        while 2 * (self.count + len(labels)) >= capacity:
            capacity *= 2
        if capacity != len(self.used):
            require_allocation("orbit registry", (capacity, self.order, 4))
            keys = np.empty((capacity, self.order, 4), dtype=np.int64)
            used = np.zeros(capacity, dtype=np.uint8)
            registry_insert(self.keys[self.used != 0], keys, used)
            self.keys, self.used = keys, used
        self.count += registry_insert(labels, self.keys, self.used)


def _prepare_cluster_labels(
    labels: tuple[tuple[int, int, int, int], ...], symmetry: PrimitiveSymmetry
) -> np.ndarray:
    """Validate cluster labels for primitive symmetry transformations.

    ``labels`` must have shape ``(p, 4)`` with rows ``(site, tx, ty, tz)``.
    Site indices must refer to the primitive motif, and all affine symmetry
    transformations and subsequent re-anchoring must remain within the
    supported integer range.

    Returns
    -------
    ndarray
        Validated ``int64`` cluster labels.

    Raises
    ------
    ValueError
        If the label layout or primitive-site indices are invalid.
    OverflowError
        If a transformed or re-anchored lattice translation cannot be
        represented safely.
    """
    array = as_int64_array(labels, name="primitive cluster labels")
    from mlfcs.geometry.symmetry import validate_site_actions

    if array.ndim != 2 or array.shape[1] != 4 or not len(array):
        raise ValueError("cluster labels must have shape (order,4) with positive order")
    if np.any(array[:, 0] < 0) or np.any(array[:, 0] >= symmetry.site_permutations.shape[1]):
        raise ValueError("cluster label site lies outside primitive motif")
    validate_site_actions(
        array[:, 1:], symmetry.rotations, symmetry.site_shifts[:, array[:, 0], :], reanchor=True
    )
    return array


def compute_orbit_actions(
    cluster: Cluster,
    symmetry: PrimitiveSymmetry,
    permutation_values: tuple[tuple[int, ...], ...],
    permutation_array: np.ndarray,
) -> tuple[
    Cluster,
    tuple[Cluster, ...],
    np.ndarray,
    np.ndarray,
    tuple[tuple[np.ndarray, tuple[int, ...]], ...],
]:
    """Construct the symmetry orbit and stabilizer of a cluster.

    Every primitive-cell symmetry operation is combined with every allowed
    tensor-axis permutation and applied to ``cluster``. Transformed images are
    re-anchored so that clusters differing only by a common lattice
    translation have the same representation.

    The distinct transformed clusters form the orbit ``O(C) = {g C}``, while
    actions satisfying ``g C = C`` form the stabilizer of the representative
    cluster. For each distinct image, the first generating action is retained.

    Parameters
    ----------
    cluster
        Representative force-constant cluster.
    symmetry
        Primitive-cell symmetry operations acting on motif sites and lattice
        translations.
    permutation_values
        Allowed tensor-axis permutations as Python tuples.
    permutation_array
        The same permutations as an integer array of shape ``(q, p)``.

    Returns
    -------
    representative
        The input cluster, unchanged.
    clusters
        Distinct symmetry-equivalent cluster images.
    operations
        Primitive symmetry-operation index associated with each retained image.
    permutations
        Tensor-axis permutation associated with each retained image.
    stabilizers
        All ``(rotation, permutation)`` actions that leave the representative
        cluster unchanged.

    Raises
    ------
    RuntimeError
        If no stabilizer action is found, which indicates an invalid primitive
        symmetry description because the identity action must stabilize every
        cluster.
    """
    labels = _prepare_cluster_labels(cluster.labels, symmetry)
    require_allocation("orbit actions", (symmetry.size * len(permutation_values), cluster.order, 4))
    transformed = transform_cluster(
        labels,
        symmetry.rotations,
        symmetry.site_permutations,
        symmetry.site_shifts,
        permutation_array,
    )
    representative = cluster
    require_allocation(
        "orbit action deduplication", (max(2, 2 * len(transformed)), cluster.order, 4)
    )
    indices, stabilizer_indices = distinct_orbit_actions(transformed, labels)
    permutation_count = len(permutation_values)
    clusters = tuple(Cluster.from_labels(transformed[index]) for index in indices)
    operations = np.asarray(indices // permutation_count, dtype=np.int64)
    permutations = permutation_array[indices % permutation_count]
    stabilizers = tuple(
        (
            symmetry.rotations[index // permutation_count],
            permutation_values[index % permutation_count],
        )
        for index in stabilizer_indices
    )
    if not stabilizers:
        raise RuntimeError("the primitive symmetry group does not contain the identity action")
    return representative, clusters, operations, permutations, stabilizers
