"""Exact reciprocal labels and their irreducible stars.

For a row-vector supercell matrix ``S``, a reciprocal label ``l / D`` belongs
to its grid when ``l @ S.T == 0 (mod D)``, where ``D = abs(det(S))``.  The labels
and their symmetry actions are integer facts; floating q coordinates are only
formed when a later Fourier calculation needs them.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass

import numpy as np

from mlfcs.core import PrimitiveSymmetry
from mlfcs.core.algebra.exact import to_python_rows
from mlfcs.core.algebra.integer import adjugate_3x3, determinant_3x3, rotate_q_labels
from mlfcs.core.log_error import get_logger

logger = get_logger(__name__)


def _matrix(source: object) -> np.ndarray:
    rows = to_python_rows(source)
    if len(rows) != 3 or any(len(row) != 3 for row in rows):
        raise ValueError("supercell matrix must be a 3 by 3 integer matrix")
    # The existing core algebra uses int64 inputs and exact Python-integer
    # intermediates.  In particular, an object-typed Supercell.matrix is valid.
    values = np.asarray(rows, dtype=np.int64)
    if determinant_3x3(values) == 0:
        raise ValueError("supercell matrix must be nonsingular")
    values.setflags(write=False)
    return values


@dataclass(frozen=True, slots=True)
class QGrid:
    """All reciprocal characters of one integer supercell lattice.

    ``labels`` are lexicographically ordered numerators in ``[0, D)^3``.  The
    order is independent of atom ordering and of how the same row lattice is
    based.  No HNF or floating-point q matching is needed.
    """

    matrix: np.ndarray
    labels: np.ndarray
    denominator: int

    @classmethod
    def from_matrix(cls, matrix: object) -> QGrid:
        """Enumerate the dual quotient generated by rows of ``adj(S).T``."""
        values = _matrix(matrix)
        denominator = abs(determinant_3x3(values))
        adjugate = adjugate_3x3(values)
        generators = [tuple(int(value) % denominator for value in row) for row in adjugate.T]
        zero = (0, 0, 0)
        labels = {zero}
        pending = deque([zero])
        while pending:
            label = pending.popleft()
            for generator in generators:
                image = tuple(
                    (value + step) % denominator
                    for value, step in zip(label, generator, strict=True)
                )
                if image not in labels:
                    labels.add(image)
                    pending.append(image)
        if len(labels) != denominator:
            raise RuntimeError("reciprocal quotient has the wrong number of characters")
        ordered = np.asarray(sorted(labels), dtype=np.int64)
        products = ordered.astype(object) @ values.T.astype(object)
        if any(int(value) % denominator for value in products.flat):
            raise RuntimeError("reciprocal quotient contains a label outside the dual lattice")
        ordered.setflags(write=False)
        result = cls(values, ordered, denominator)
        logger.info(
            "Reciprocal grid built: matrix=%s determinant=%d qpoints=%d",
            values.tolist(),
            denominator,
            result.size,
        )
        return result

    @property
    def points(self) -> np.ndarray:
        """Fractional q coordinates in the exact label order."""
        return self.labels.astype(np.float64) / self.denominator

    @property
    def size(self) -> int:
        return len(self.labels)


def _compatible(
    matrix: np.ndarray, adjugate: np.ndarray, rotation: np.ndarray, denominator: int
) -> bool:
    """Test ``S R.T S^-1`` for integer entries with Python integers."""
    product = matrix.astype(object) @ rotation.T.astype(object) @ adjugate.astype(object)
    return all(int(value) % denominator == 0 for value in product.flat)


@dataclass(frozen=True, slots=True)
class QStars:
    """Irreducible q stars and the exact route to every member.

    ``representatives`` index ``grid.labels``.  ``star_of``, ``operations``
    and ``antiunitary`` have one entry per full-grid label; they are indexing
    data, not a second Fourier evaluation path.  ``operations`` index the
    supplied primitive symmetry, including its translation and site action.
    """

    grid: QGrid
    symmetry: PrimitiveSymmetry
    representatives: np.ndarray
    star_of: np.ndarray
    operations: np.ndarray
    antiunitary: np.ndarray
    weights: np.ndarray
    time_reversal: bool

    @classmethod
    def from_symmetry(
        cls, grid: QGrid, symmetry: PrimitiveSymmetry, *, time_reversal: bool = True
    ) -> QStars:
        """Partition the grid under its lattice-preserving point operations."""
        if not isinstance(grid, QGrid) or not isinstance(symmetry, PrimitiveSymmetry):
            raise TypeError("grid and symmetry must be QGrid and PrimitiveSymmetry")
        n = grid.size
        labels = grid.labels
        denominator = grid.denominator
        lookup = {tuple(int(value) for value in label): index for index, label in enumerate(labels)}
        adjugate = adjugate_3x3(grid.matrix)
        identity = next(
            (
                index
                for index, rotation in enumerate(symmetry.rotations)
                if np.array_equal(rotation, np.eye(3, dtype=np.int32))
                and np.array_equal(symmetry.translations[index], np.zeros(3))
                and np.array_equal(
                    symmetry.site_permutations[index],
                    np.arange(symmetry.site_permutations.shape[1]),
                )
                and not np.any(symmetry.site_shifts[index])
            ),
            None,
        )
        if identity is None:
            raise ValueError("primitive symmetry does not contain the identity operation")
        compatible = [
            index
            for index, rotation in enumerate(symmetry.rotations)
            if _compatible(grid.matrix, adjugate, rotation, denominator)
        ]
        compatible.remove(identity)
        compatible.insert(0, identity)
        actions: dict[int, np.ndarray] = {}
        for operation in compatible:
            moved = rotate_q_labels(labels, symmetry.rotations[operation], denominator=denominator)
            try:
                targets = np.asarray(
                    [lookup[tuple(int(value) for value in label)] for label in moved],
                    dtype=np.int64,
                )
            except KeyError as error:
                raise RuntimeError(
                    f"grid-preserving operation {operation} maps outside the reciprocal grid"
                ) from error
            if len(np.unique(targets)) != n:
                raise RuntimeError(f"operation {operation} does not permute the reciprocal grid")
            actions[operation] = targets
        negatives = np.asarray(
            [lookup[tuple(-int(value) % denominator for value in label)] for label in labels],
            dtype=np.int64,
        )

        star_of = np.full(n, -1, dtype=np.int64)
        operations = np.full(n, -1, dtype=np.int64)
        antiunitary = np.zeros(n, dtype=bool)
        representatives: list[int] = []
        weights: list[int] = []
        for representative in range(n):
            if star_of[representative] >= 0:
                continue
            routes: dict[int, tuple[int, bool]] = {}
            for operation, permutation in actions.items():
                routes.setdefault(int(permutation[representative]), (operation, False))
            if time_reversal:
                for operation, permutation in actions.items():
                    routes.setdefault(
                        int(negatives[permutation[representative]]), (operation, True)
                    )
            members = set(routes)
            if any(star_of[member] >= 0 for member in members):
                raise RuntimeError("primitive operations do not form closed reciprocal stars")
            if any(
                int(permutation[member]) not in members
                for member in members
                for permutation in actions.values()
            ) or (
                time_reversal and any(int(negatives[member]) not in members for member in members)
            ):
                raise RuntimeError("primitive operations do not form closed reciprocal stars")
            star = len(representatives)
            for member in members:
                star_of[member] = star
                operations[member], antiunitary[member] = routes[member]
            representatives.append(representative)
            weights.append(len(members))
        if np.any(star_of < 0) or sum(weights) != n:
            raise RuntimeError("reciprocal stars do not partition the grid")
        arrays = (
            np.asarray(representatives, dtype=np.int64),
            star_of,
            operations,
            antiunitary,
            np.asarray(weights, dtype=np.int64),
        )
        for array in arrays:
            array.setflags(write=False)
        result = cls(grid, symmetry, *arrays, bool(time_reversal))
        logger.info(
            "Reciprocal stars: grid=%d irreducible=%d reduction=%.3fx "
            "time_reversal=%s symmetry_operations=%d",
            n,
            len(result.representatives),
            n / len(result.representatives),
            time_reversal,
            len(compatible),
        )
        return result

    @property
    def points(self) -> np.ndarray:
        """Only the irreducible fractional q coordinates."""
        return self.grid.points[self.representatives]

    def expand(self, values: object) -> np.ndarray:
        """Index a star-invariant spectral quantity into full-grid order."""
        array = np.asarray(values)
        if array.ndim == 0 or len(array) != len(self.representatives):
            raise ValueError("values must have one leading entry per irreducible q point")
        return array[self.star_of]

    def member_shift(self, member: int) -> tuple[int, int, int]:
        """Return the exact reciprocal lattice shift from its operation image.

        With ``r`` the representative and ``m`` the stored member label, the
        returned ``G`` satisfies ``sign * (r R^-1) = m + D G``.  This integer
        shift determines the positional gauge needed by later matrix expansion.
        """
        if not 0 <= member < self.grid.size:
            raise IndexError("member is outside the reciprocal grid")
        representative = self.grid.labels[self.representatives[self.star_of[member]]]
        operation = int(self.operations[member])
        moved = rotate_q_labels(representative, self.symmetry.rotations[operation])
        sign = -1 if self.antiunitary[member] else 1
        difference = [
            sign * int(value) - int(stored)
            for value, stored in zip(moved, self.grid.labels[member], strict=True)
        ]
        denominator = self.grid.denominator
        if any(value % denominator for value in difference):
            raise RuntimeError("star member has a nonintegral reciprocal lattice shift")
        return tuple(value // denominator for value in difference)


__all__ = ["QGrid", "QStars"]
